// FROZEN: generated from the upstream ledger service's conformance suite.
// Do not edit this file in this repository; the ledger team regenerates it.
import assert from 'node:assert/strict';
import { test } from 'node:test';
import { roundMoney } from '../src/round-money.ts';

test('ledger conformance: halves round up', () => {
  assert.equal(roundMoney(2.5), 3);
  assert.equal(roundMoney(3.5), 4);
});
